# Required libraries
library(readxl)
library(dplyr)
library(lubridate)
library(ggplot2)
library(tsibble)
library(forecast)
library(tseries)
library(tidyr)
library(reshape2)
library(scales)
library(zoo)
library(hexbin)
library(writexl)
library(stringr)

options(dplyr.width = Inf)
options(tibble.width = Inf)
options(scipen = 999)
